// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wugbrsydhzpsxljsrjnf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind1Z2Jyc3lkaHpwc3hsanNyam5mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM4MjgxNTAsImV4cCI6MjA0OTQwNDE1MH0.gwRJo4AIR0ekMB4OYidKAXcvZK_3PiBdo-XBMi6wGbs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);